import random
patient_name = input("Nhập tên bệnh nhân: ")
patient_gender = input("Nhập giới tính: ")
patient_birthdate = int(input("Nhập năm sinh: "))
patient_numberphone = input("Nhập số điện thoại: ")
patient_email = input("Nhập email: ")
patient_sick = input("Nhập triệu chứng ban đầu: ")
price = float(input("Nhập chi phí khám: ")) 
random_number = random.randint(100, 999)
patient_code = "BN" + str(patient_birthdate) + str(random_number) 

print("THẺ BỆNH NHÂN") 
print("Mã BN: ", patient_code)
print(f"Tên: {patient_name} ({type(patient_name)})")
print(f"Giới tính: {patient_gender} ({type(patient_gender)})")
print(f"Năm sinh: {patient_birthdate} ({type(patient_birthdate)})")
print(f"Điện thoại: {patient_numberphone} ({type(patient_numberphone)})")
print(f"Email: {patient_email} ({type(patient_email)})")
print(f"Triệu trứng: {patient_sick} ({type(patient_sick)})")
print(f"Chi phí: {price} VND ({type(price)})")
